### ISSUE TITLE
How To auto-generate Ctags Include Python site-packages

### ISSUE THREAD

**Issue by twocucao** [skywind3000/gutentags_plus#1]
I need to browse my codebase with django app and django source code

How can i generate ctags with vim-gutentags like this?

```
ctags -R --fields=+l --languages=python --python-kinds=-iv -f ./.tags $(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))")
```
Thanks

**Comment by skywind3000** [comment]
自己先生成一个 pylibs.tags ，放到 ~/.vim/tags 里面，vimrc 中 set tags+=~/.vim/tags/pylibs.tags，还可以做一个autocmd，发现 filetype 是python文件的时候再 setlocal tags+=~/.vim/tags/pylibs.tags

**Comment by twocucao** [comment]
谢谢啦
