### ISSUE TITLE
用GscopeFind查找哪些函数调用此函数后， 光标还在xxxx函数处，要应该设置光标，自动跳到quickfix窗口，等到用户上下，进行选中查看结果。

### ISSUE THREAD

**Issue by hawkinchina** [skywind3000/gutentags_plus#13]
光标停在函数xxxx名上；
采用快捷键：<leader>cc 
用GscopeFind查看有哪些函数调用了该函数xxxx此函数， 
quickfix窗口弹出，列出了很多查询结果；
就在这个时刻：
光标焦点还在xxxx函数的处，是否可以设置光标，让它自动跳到quickfix窗口，等到用户上下，进行选中查看结果？？

**Comment by hawkinchina** [comment]
楼主可以对照一个leaderF，查询结果，弹出下面的窗口后，上下方向键（ctrl  +  j/k） 移动浏览，同时按esc即可关闭弹出窗口，极其流畅。。也符合使用者的习惯。
-  leaderF 除了搜索mru弹出窗口，按esc键无法取消弹出窗口（其他都ok），但是此时你按q键，可以关闭窗口。

**Comment by skywind3000** [comment]
```VimL
let g:gutentags_plus_switch = 1
```

你就可以自动切换到 quickfix 了，leaderf是自己做的结果窗口，这里用的 quickfix 是 vim 系统提供的标准组件，用标准组件而非自己实现的好处就在于，有大量插件围绕 quickfix 这个标准组件提供辅助操作，比如我写的 vim-preview ，可以在 quickfix 里面方便按p预览，比如其他人写的可以在 quickfix 上自动高亮对应代码文件里的行号。还有人写了插件可以在状态栏上显示quickfix的结果缩略。quickfix还可以保存到文件之类。

这就是quickfix的作用，你可以三句话就在 quickfix 上实现按q退出，对 vim 用户来讲不是很简单的么。

**Comment by skywind3000** [comment]
注意更新下，修正了个bug

**Comment by hawkinchina** [comment]
韦大侠: 咨询一下， gutentags_plus使用， 其实是取代了cscope 原有的链接。。能否保持cscope的原有连接， 再新增加到gutentags的连接。 这样cscope 原有的连接，和 gutentags新增加的连接都可以使用？？

**Comment by skywind3000** [comment]
你已经没有必要用cscope了，还用了干嘛？
