### ISSUE TITLE
c language search path setting

### ISSUE THREAD

**Issue by xiaocang** [skywind3000/gutentags_plus#14]
看了文档后还是不太明白，如何添加其他路径到 ctags 参数中。
例如要跳转到 `stdio.h` 中的 `printf` 函数。
可以在 `.gutctags` 文件中添加路径吗，好像没找到相关参数项。

**Comment by skywind3000** [comment]
你要阅读 gutentags 的文档。不是本插件负责。

**Comment by xiaocang** [comment]
thx
