### ISSUE TITLE
ERROR: no gtags database for this project, check gutentags's documents

### ISSUE THREAD

**Issue by nqiu** [skywind3000/gutentags_plus#21]
I followed the README.md file and configured vim as follows, 

> " gutentags --------------------------
> " enable gtags module
> let g:gutentags_modules = ['ctags', 'gtags_cscope']
> 
> " config project root markers.
> let g:gutentags_project_root = ['.root', '.git', '.svn', '.hg', '.project']
> 
> " generate datebases in my cache directory, prevent gtags files polluting my project
> let g:gutentags_cache_dir = expand('~/.cache/tags')
> 
> " change focus to quickfix window after search (optional).
> let g:gutentags_plus_switch = 1

but Vim complained "gutentags: gtags-cscope job failed, returned: 122" when I opened a .py file. The `ctrl + ]` worked, but not `<leader>cs` or `GscopeFind c <func_name>`. It complained "ERROR: no gtags database for this project, check gutentags's documents"

**Comment by nqiu** [comment]
@skywind3000 Could you help me, please? Thanks a lot in advance~

**Comment by nqiu** [comment]
This issue was caused by the lack of `gtags-cscope` on my Mac,
and it was resolved by installing `global` on Mac.
`brew install global`

**Comment by sachingns** [comment]
Hi How to solve this issue
**ERROR: no gtags database for this project, check gutentags's documents**

**Comment by nqiu** [comment]
> Hi How to solve this issue
> **ERROR: no gtags database for this project, check gutentags's documents**

The root cause for my case was that the executable binary of `gtags-cscope`(which is included in the `global` package) was missing on my MacOS.  You can try to install the `global` package to solve the problem by running the following commands in shell:
`(MacOS) $ brew install global`
`(Ubuntu) $ sudo apt install global`

**Comment by Lim-LinYuanbo** [comment]
Why is it always prompted “no gtags database for this project...”

my source code path:`/mnt/e/project/rt-thread`, The `.git` in rt-thread root directory.
The `.cache/tags/mnt-e-project-rt-thread-.tags` is generated.
I has been install global.

Please help me, thx a lot.
