### ISSUE TITLE
GscopeFind查找类名、对象成员函数和变量等均失败

### ISSUE THREAD

**Issue by fly-potato-100** [skywind3000/gutentags_plus#22]
会提示
E259: not find 'nCount'
E259: not find 'PrintMe'
E259: not find 'MyClass1'
类似这样的错误。

我用gtags --dump查看了G*等文件
GTAGS里面没有这些符号
GRTAGS里面却可以找到
不知道是不是我哪里配错了？其他全局变量、全局函数、namespace是可以正常GscopeFind到的

**Comment by fly-potato-100** [comment]
我尝试把.h文件改成了.hpp，似乎可以正常工作了，这是因为文件后缀名的原因吗？是否有比较优雅的解决方式呢？

**Comment by skywind3000** [comment]
设置环境变量：GTAGSFORCECPP 等于 1

**Comment by fly-potato-100** [comment]
> 这是你自己不会用 gtags，没有看它的说明，
> 设置环境变量：GTAGSFORCECPP 等于 1

工作正常了，谢大佬！

**Comment by fly-potato-100** [comment]
> 这是你自己不会用 gtags，没有看它的说明，
> 设置环境变量：GTAGSFORCECPP 等于 1

工作正常了，谢大佬！
