### ISSUE TITLE
Solution of error "E259: not found 'xxx'" on some filetypes

### ISSUE THREAD

**Issue by PetrusZ** [skywind3000/gutentags_plus#3]
#### 原因：
gtags/global最多可支持50+种文件格式，但默认只支持6种。支持其他的格式需要开启扩展支持。

#### 步骤：
1. gtags/global建议安装6.6.0以上版本。（个人测试6.5.7也可以）
2. 安装pygments。（通过pip或包管理系统安装都可以）
3. 在vim的配置文件中添加2个环境变量。（gtags.conf可在`/usr/share`或`/usr/local/share`等目录下找到）
```vimL
let $GTAGSLABEL = 'native-pygments'
let $GTAGSCONF = '/path/to/share/gtags/gtags.conf'
```
4. 如果之前在vim中打开过project，需要在`~/.cache/tags`删除该project的缓存重新尝试。

#### debug/troubleshooting：
* `:set tags? `命令可检查tags文件是否挂载
* `:echo tagfiles()`命令可检查当前buffer的tags文件列表
* `:echo taglist('符号名称')`命令可检查该符号所匹配的tags
* 检查`~/.cache/tags`目录下，project的GTAGS文件的大小。如为16KB则表示gtags数据库中无数据，gtags无法查找到符号

参考：更多资料可见作者的知乎专栏中的文章，[Vim 8 中 C/C++ 符号索引：从 GTags 到 LanguageServer](https://zhuanlan.zhihu.com/p/36279445)

**Comment by hankji** [comment]
我发现在vimrc配置文件中添加一行:
set cscopeprg='gtags-cscope'
就正常了. 具体原理不懂, 哈哈.
