### ISSUE TITLE
[Feature Request] Add support to generate for multi directories/repos

### ISSUE THREAD

**Issue by v-cam** [skywind3000/gutentags_plus#37]
# Currently Issue
I work with a really **huge** codebase -- `AOSP`, and only interested in a few directories. Currently, I use the `find`+ `gtags` command to generate the tags for those files that I'm care about.

# Feature Request
Can you supply a way, which we can  add the direcotry we concerned about. For example, by giving a `gutentags_work_directory` paramters, user can add their desired directory into the list, and the plugin can auto generate tags for those directories.

**Comment by skywind3000** [comment]
Gutentags_plus has nothing todo with this, ask gutentags directly.

**Comment by v-cam** [comment]
> Gutentags_plus has nothing todo with this, ask gutentags directly.

Thanks for reply. Sorry to disturb.
