### ISSUE TITLE
感觉在重复造轮子，相比gtags-cscope的优势是啥？

### ISSUE THREAD

**Issue by ZiYang-oyxy** [skywind3000/gutentags_plus#47]
用了一段时间，发现一些易用性问题（例如连续两次查找，quickfix窗口就会缩成很小的高度，由于不熟悉vimL，花了很多时间才自己修复了），后来发现**完全是被带偏了**。

gtags自带的gtags-cscope.vim在vim中本来就集成得很好，可以无缝替换vim中的cscope命令（好处是vim cscope有关所有的易用性的问题，你几乎都可以从社区找到解决方案，比如quickfix窗口的配置），只是需要从gtags源码仓里面把源码文件捞出来放到vim的plugin文件夹下，例如： http://cvs.savannah.gnu.org/viewvc/*checkout*/global/global/gtags-cscope.vim?pathrev=VERSION-6_6_7

以下是我替换gtags-cscope.vim后的.vimrc配置（需要提前将gtags-cscope.vim放到vim的plugin文件夹）：

```
if has("cscope")
    set csto=1
    set cst
    set nocsverb
    set csverb
    set cscopequickfix=s-,g-,c-,t-,e-,f-,i-,d-
endif

"s: Find this C symbol
"g: Find this definition
"c: Find functions calling this function
"t: Find this text string
"d: Find functions called by this function
"e: Find this egrep pattern
"f: Find this file
"i: Find files #including this file
noremap <C-@>s :cs find s <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>g :cs find g <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>c :cs find c <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>t :cs find t <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>d :cs find d <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>e :cs find e <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
noremap <C-@>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>

function! SwitchSourceHeader()
    cs find f %:t:r.h
endfunction
noremap <C-@>h :call SwitchSourceHeader()<CR>

" Open a fully width quickfix window at the bottom of vim
Plug 'milkypostman/vim-togglelist'
let g:toggle_list_no_mappings=1
nmap <script> <silent> <F9> :call ToggleQuickfixList()<CR>
```

**Comment by skywind3000** [comment]
麻烦先了解下本插件的工作流：

https://zhuanlan.zhihu.com/p/36279445

**Comment by lircn** [comment]
@ZiYang-oyxy 最终还有采用ctags + 手动生成tags吗？

**Comment by ZiYang-oyxy** [comment]
> @ZiYang-oyxy 最终还有采用ctags + 手动生成tags吗？

直接用gutentags，天然就挺好用的

" brew install global
" brew install universal-ctags
if !(has('job') || (has('nvim') && exists('*jobwait')))
else
    Plug 'ludovicchabant/vim-gutentags'
endif

if has("cscope")
    set csto=1
    set cst
    set nocsverb
    set csverb
    set cscopequickfix=s-,g-,c-,t-,e-,f-,i-,d-
endif
"s: Find this C symbol
"g: Find this definition
"c: Find functions calling this function
"t: Find this text string
"d: Find functions called by this function
"e: Find this egrep pattern
"f: Find this file
"i: Find files #including this file
noremap <C-@>s :cs find s <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>g :cs find g <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>c :cs find c <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>t :cs find t <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>d :cs find d <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>e :cs find e <C-R>=expand("<cword>")<CR><CR>
noremap <C-@>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
noremap <C-@>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
function! SwitchSourceHeader()
    cs find f %:t:r.h
endfunction
noremap <C-@>h :call SwitchSourceHeader()<CR>
map <F6> :cs find g<space>

" enable gtags module
let g:gutentags_modules = ['ctags', 'gtags_cscope']

" config project root markers.
let g:gutentags_add_default_project_roots=0
let g:gutentags_project_root = ['.root', '.git']
let g:gutentags_generate_on_empty_buffer=1

"" generate datebases in my cache directory, prevent gtags files polluting my project
"let g:gutentags_cache_dir = expand('~/.awesome_devops/vim/cache/tags')

set statusline+=%{gutentags#statusline()}

" Useful debug
"let g:gutentags_trace = 1

let g:gutentags_ctags_exclude = [
    \ '*/freebsd/*',
    \ '*/windows/*'
\]

**Comment by skywind3000** [comment]
> gutentags已经解决了第一个问题，而第二个问题可能我没怎么遇到吧，有些用git submodule的场景，只要符号没有太多重名，影响也不大，第三个问题也是不太遇到。

第二第三才是问题的核心，你一个 ”没遇到“，说明你根本没理解这个问题在哪里，或者说你的使用场景很单一，不存在同时编辑多个项目的情况，比如你一个项目只开一个 vim，并且就在项目根目录下打开之类，是没问题，但场景太过单一。
