### ISSUE TITLE
quickfix中的每行都显示搜索关键字没有必要

### ISSUE THREAD

**Issue by qindapao** [skywind3000/gutentags_plus#54]
![image](https://github.com/skywind3000/gutentags_plus/assets/109883544/dc954dd5-df25-41a5-88fa-9cef843ab143)

你好，紫色的部分已经显示了当前搜索的关键字了。然后红色的框的部分，每行都显示这个关键字感觉没有必要，占用屏幕空间，而且如果高亮后就会看起来很乱？请问可以去掉这个显示吗？或者提供一个配置开关关闭它？

**Comment by skywind3000** [comment]
去不掉，这是 cscope 接口就是这么显示的，要去掉你要改 vim 代码。

**Comment by qindapao** [comment]
好的👌知道了，问题也不大。谢谢哈，这个插件很好用。
