### ISSUE TITLE
Handling exception

### ISSUE THREAD

**Issue by menash134** [skywind3000/gutentags_plus#55]
![gutentags](https://github.com/skywind3000/gutentags_plus/assets/16444146/e143723a-e70d-46dc-89ad-f23e851ef92b)

Hi ,
Could you please help me in catching this exception and handle quietly .

**Comment by skywind3000** [comment]
Environment please, vim or nvim? version?
Use my fork of `vim-gutentags` please:

https://github.com/skywind3000/vim-gutentags

**Comment by menash134** [comment]
I was using then the ludo/guten-tags, now I switched over to your guten tags. Now my exception message changes

![gutentags_now](https://github.com/skywind3000/gutentags_plus/assets/16444146/1890457d-6095-4baf-bbfb-9c855903013e)


NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info


Below is the configuration related to gutentags.
![settings_gutentags](https://github.com/skywind3000/gutentags_plus/assets/16444146/d6148e8b-1eac-4924-8d05-de836d80cb63)

**Comment by skywind3000** [comment]
restart your neovim

**Comment by menash134** [comment]
actually i made generate_on_missing to zero and then the error is gone. Thanks for your help and response. That was really kind.
